name: Go Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    name: 'go-test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Postgres'
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo -u postgres psql -c "CREATE USER ${{ secrets.TEST_DB_USER }} WITH PASSWORD  '${{ secrets.TEST_DB_PASSWORD }}'"
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.TEST_DB_NAME }}"
          sudo -u postgres psql -c "ALTER ROLE ${{ secrets.TEST_DB_USER }} SUPERUSER"
          sudo systemctl restart postgresql

      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'
      - name: Run Go Test
        env:
          TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
        run: |
          go test -v ./...